### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by Xoeseko** [Xoeseko/sdg.market#5]
- [x] Use github pages and jekyll to deploy an informative website for sdg.market
- [x] Work on header menu for site navigation...
- [x] Add images to whitepaper
- [x] Create report website with sections for the different steps of the project we are going to do
- [x] Make the files in _posts folder accessible on the homepage... Should be straightforward. The finality would be that each one of us is able to write a report on our work in the project in the form of a "blog post"
- [x] Understand jekyll and personalize the theme to our taste something fitting as documentation for the main [sdg innovation market](//sdg-market.oniabsis.com) Maybe take inspiration from the color scheme... So that they can link to our documentation on the main app.
- [x] Is there a logo to work with ?

**Comment by Xoeseko** [comment]
[embedding d3 visualisations](https://www.quantamagazine.org/new-ai-strategy-mimics-how-brains-learn-to-smell-20180918/)

**Comment by Xoeseko** [comment]
I like this [theme](https://github.com/mx3m/hikari-for-jekyll) a bit better than our current one... Can we take inspiration from it or even simply implement it ?

**Comment by Bayar4B** [comment]
I don't understand how to implement this theme. Am i supposed to just import all the files from the project or just change our config.yml ?

**Comment by Xoeseko** [comment]
Try it out in your branch... If you change the theme in config.yml what happens ? I suspect the theme is not supported by github so you would have to copy the config files from the repo... But if it is supported by github you should be able to use it. Read the documentation to make sure and try stuff that's the best way to learn. You don't have to implement this theme in particular but I found it interesting

**Comment by Sofia-Pika** [comment]
I can't see the pics in the whitepaper...
I get an error 404 for each pic i click on.

**Comment by Xoeseko** [comment]
hmm that's curious..? In the main branch ?
